;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Building.Requires.A",DevComment="")
+GameplayTagList=(Tag="Building.Requires.B",DevComment="")
+GameplayTagList=(Tag="Building.Requires.C",DevComment="")
+GameplayTagList=(Tag="Zone.Type.A",DevComment="")
+GameplayTagList=(Tag="Zone.Type.B",DevComment="")
+GameplayTagList=(Tag="Zone.Type.C",DevComment="")

