;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Building.Requires.A",NewTagName="Building.Resources.A")
+GameplayTagRedirects=(OldTagName="Building.Requires.B",NewTagName="Building.Resources.B")
+GameplayTagRedirects=(OldTagName="Building.Requires.C",NewTagName="Building.Resources.C")
+GameplayTagRedirects=(OldTagName="Building.Requires",NewTagName="Building.Resources")
+GameplayTagList=(Tag="Building.Resources.A",DevComment="")
+GameplayTagList=(Tag="Building.Resources.B",DevComment="")
+GameplayTagList=(Tag="Building.Resources.BusyWorkers",DevComment="")
+GameplayTagList=(Tag="Building.Resources.C",DevComment="")
+GameplayTagList=(Tag="Building.Resources.HumanResources",DevComment="")
+GameplayTagList=(Tag="Zone.Type.A",DevComment="")
+GameplayTagList=(Tag="Zone.Type.B",DevComment="")
+GameplayTagList=(Tag="Zone.Type.C",DevComment="")

